package com.ort.howlingwolf.domain.model.village.setting

import com.ort.dbflute.allcommon.CDef
import com.ort.howlingwolf.domain.model.message.MessageType
import com.ort.howlingwolf.domain.model.village.VillageDays
import java.time.LocalDateTime

data class VillageSettings(
    val capacity: PersonCapacity,
    val time: VillageTime,
    val charachip: VillageCharachip,
    val organizations: VillageOrganizations,
    val rules: VillageRules,
    val password: VillagePassword
) {

    companion object {

        fun createAutoGeneratedForRegister(
            organization: String,
            startDatetime: LocalDateTime,
            silentHours: Int?,
            availableDummySkill: Boolean,
            forBeginner: Boolean,
            canSkillRequest: Boolean
        ): VillageSettings {
            val min = organization.split("\n").first().length
            val max = organization.split("\n").last().length
            return VillageSettings(
                capacity = PersonCapacity(
                    min = min,
                    max = max
                ),
                time = VillageTime(
                    termType = CDef.Term.長期.code(),
                    prologueStartDatetime = LocalDateTime.now(),
                    epilogueDay = null,
                    epilogueStartDatetime = null,
                    startDatetime = startDatetime,
                    dayChangeIntervalSeconds = 86400,
                    silentHours = silentHours
                ),
                charachip = VillageCharachip(
                    dummyCharaId = 1,
                    charachipId = 1
                ),
                organizations = VillageOrganizations(
                    organization = organization.split("\n").associate {
                        it.length to it
                    }
                ),
                rules = VillageRules(
                    openVote = false,
                    availableSkillRequest = canSkillRequest,
                    availableSpectate = false,
                    openSkillInGrave = false,
                    visibleGraveMessage = false,
                    availableSuddenlyDeath = true,
                    availableCommit = true,
                    availableDummySkill = availableDummySkill,
                    forBeginner = forBeginner,
                    messageRestrict = VillageMessageRestricts(
                        existRestricts = true,
                        restrictList = listOf(
                            VillageMessageRestrict(
                                type = MessageType(CDef.MessageType.通常発言),
                                count = if (forBeginner) 10 else 20,
                                length = 200
                            ),
                            VillageMessageRestrict(
                                type = MessageType(CDef.MessageType.人狼の囁き),
                                count = 40,
                                length = 200
                            ),
                            VillageMessageRestrict(
                                type = MessageType(CDef.MessageType.独り言),
                                count = 100,
                                length = 200
                            ),
                            VillageMessageRestrict(
                                type = MessageType(CDef.MessageType.死者の呻き),
                                count = 100,
                                length = 200
                            )
                        )
                    )
                ),
                password = VillagePassword(
                    joinPasswordRequired = false,
                    joinPassword = null
                )
            )
        }
    }

    fun existsDifference(setting: VillageSettings): Boolean {
        return capacity.existsDifference(setting.capacity)
                || time.existsDifference(setting.time)
                || organizations.existsDifference(setting.organizations)
                || rules.existsDifference(setting.rules)
                || password.existsDifference(setting.password)
    }

    fun extendPrologue(): VillageSettings {
        return this.copy(time = time.extendPrologue())
    }

    fun toEpilogue(villageDays: VillageDays): VillageSettings {
        return this.copy(
            time = time.toEpilogue(villageDays)
        )

    }
}